name: 'Amazon ECS Standalone Task deployment for GitHub Actions'
description: 'Runs a standalone Amazon ECS task'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  task-definition:
    description: 'The name of ECS task definition'
    required: true
  cluster:
    description: "The name of the ECS cluster. Will default to the 'default' cluster"
    required: false
  count:
    description: "The count of tasks to run. Will default to the 1"
    required: true
  subnets:
    description: "A space separated list of subnets to which the task should be attached, required for tasks with awsvpc network mode"
    required: false
  started-by:
    description: "The value of the task started-by"
    required: false
  wait-for-finish:
    description: "Whether to wait for tasks to reach stopped state. Will default to not waiting"
    required: false
  wait-for-minutes:
    description: 'How long to wait for the task reach stopped state, in minutes (default: 30 minutes, max: 6 hours).'
    required: false
  security-groups:
    description: "The IDs of the security groups associated with the task or service (space separated), required for tasks with awsvpc network mode."
    required: false
  assign-public-ip:
    description: "Whether the task’s elastic network interface receives a public IP address."
    required: false
    default: ENABLED
  launch-type:
    description: "The infrastructure where your task runs on. Possible values: EC2, FARGATE, or EXTERNAL"
    required: false
    default: FARGATE
outputs:
  task-definition-arn:
    description: 'The ARN of the registered ECS task definition'
  task-arn:
    description: 'The ARN of the ECS task'
runs:
  using: 'node16'
  main: 'dist/index.js'
